-- 회원
ALTER TABLE "HAW"."MEMBER"
	DROP CONSTRAINT IF EXISTS "PK_MEMBER"; -- 회원 기본키

-- 회원
DROP TABLE IF EXISTS "HAW"."MEMBER";

-- 회원
CREATE TABLE "HAW"."MEMBER"
(
	"MEMBER_NO"  SERIAL      NOT NULL DEFAULT nextval('SEQ_MEMBER'), -- 회원번호
	"NAME"       VARCHAR(50) NOT NULL, -- 이름
	"EMAIL"      VARCHAR(40) NOT NULL, -- 이메일
	"PASSWORD"   VARCHAR(20) NOT NULL, -- 비밀번호
	"NICKNAME"   VARCHAR(50) NOT NULL, -- 닉네임
	"IP"         VARCHAR(40) NULL,     -- 아이피
	"INPUT_DT"   DATE        NOT NULL, -- 등록일
	"TIME_STAMP" DATE        NOT NULL  -- 수정일
)
WITH (
OIDS=false
);

ALTER SEQUENCE "SEQ_MEMBER" OWNED BY "HAW"."MEMBER"."MEMBER_NO";

-- 회원
COMMENT ON TABLE "HAW"."MEMBER" IS '회원';

-- 회원번호
COMMENT ON COLUMN "HAW"."MEMBER"."MEMBER_NO" IS '회원번호';

-- 이름
COMMENT ON COLUMN "HAW"."MEMBER"."NAME" IS '이름';

-- 이메일
COMMENT ON COLUMN "HAW"."MEMBER"."EMAIL" IS '이메일';

-- 비밀번호
COMMENT ON COLUMN "HAW"."MEMBER"."PASSWORD" IS '비밀번호';

-- 닉네임
COMMENT ON COLUMN "HAW"."MEMBER"."NICKNAME" IS '닉네임';

-- 아이피
COMMENT ON COLUMN "HAW"."MEMBER"."IP" IS '아이피';

-- 등록일
COMMENT ON COLUMN "HAW"."MEMBER"."INPUT_DT" IS '등록일';

-- 수정일
COMMENT ON COLUMN "HAW"."MEMBER"."TIME_STAMP" IS '수정일';

-- 회원 기본키
CREATE UNIQUE INDEX "PK_MEMBER"
	ON "HAW"."MEMBER"
	( -- 회원
		"MEMBER_NO" ASC -- 회원번호
	)
;
-- 회원
ALTER TABLE "HAW"."MEMBER"
	ADD CONSTRAINT "PK_MEMBER"
		 -- 회원 기본키
	PRIMARY KEY 
	USING INDEX "PK_MEMBER";

-- 회원 기본키
COMMENT ON CONSTRAINT "PK_MEMBER" ON "MEMBER" IS '회원 기본키';